#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/redis

# - name: Update apt cache
#   notify:
#   apt:
#     update_cache: yes

- name: Install Redis
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - redis-server

- name: Ensure redis is started and enable
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: yes

- name: Backup original Redis configuration file
  copy:
    src: "{{ redis_conf_path }}"
    dest: "{{ redis_conf_path }}.backup"
    remote_src: yes

- name: Configure Redis AUTH
  blockinfile:
    path: /etc/redis/redis.conf
    create: yes
      # bind 127.0.0.1
      # port 6379
    block: |
      requirepass "{{ REDIS_PASSWORD }}"
    marker: "# {mark} ANSIBLE-MANAGED CONFIGURATION"

- name: Ensure Redis configuration has maxmemory set
  lineinfile:
    path: "{{ redis_conf_path }}"
    regexp: '^maxmemory '
    line: "maxmemory {{ maxmemory }}"
    state: present

- name: Ensure Redis eviction policy is set
  lineinfile:
    path: "{{ redis_conf_path }}"
    regexp: '^maxmemory-policy '
    line: "maxmemory-policy {{ maxmemory_policy }}"
    state: present

- name: Allow Redis to listen on all interfaces
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind '
    line: 'bind 0.0.0.0 ::0'
    # line: 'bind 127.0.0.1'
    insertafter: '^bind '
    state: present
    backup: yes

- name: Restart Redis to apply changes
  ansible.builtin.service:
    name: redis-server
    state: restarted
    enabled: yes