---

### ADD YOUR VARIABLES

debug_msg : This is the debug msg from database-srv

### Template

# Redis Auth
REDIS_PASSWORD: "7e024176-3c36-4e6e-89ac-ea608a41e40bb7725410-c8ca-47fa-b2b9-385f4305dcd3"

# MariaDB Root User Account
mariadb_root_user : root
mariadb_root_user_password: rO0tU5eRP@ss.4devo_T3@m

# MySQL Root User Account
mysql_root_user : root
mysql_root_user_password : rO0tU5eRP@ss.4devo_T3@m


# SFSA : Simple Full-Stack Application
mysql_SFSA_database: 
mysql_SFSA_user: 
mysql_SFSA_password: 

mysqldb_SFSA_database: 
mysqldb_SFSA_user: 
mysqldb_SFSA_password: 


mysql_users: 

  - username: 
    database_name: 
    privileges: 
    password: 
    host : 

  # - username: 
  #   database_name: 
  #   privileges: 
  #   password: 
  #   host : 
