Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  machines = {
    "local"    => "192.168.56.155"
    # ,
    # "production"    => "192.168.56.200",
    # "staging"    => "192.168.56.201",
    # "test"    => "192.168.56.202"
  }

  machines.each do |name, ip|

    config.vm.define name do |machine|

      machine.vm.hostname = name
      machine.vm.network "private_network", ip: ip
      machine.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end

      config.vm.synced_folder "./machines_shared_folder", "/vagrant_data"

      machine.vm.provision "shell", inline: <<-SHELL

        # Try to enable password connexion via SSH
        sudo sed -i 's/^#PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo sed -i 's/^# PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        
        sudo systemctl restart sshd
        
        echo "vagrant:vagrant" | sudo chpasswd

        # apt-get update

      SHELL

      # machine.vm.provision :ansible do |ansible|
      #   ansible.playbook = "../playbook.yml"
      #   ansible.inventory_path = "../inventories/local"
      #   ansible.become = true
      # end

    end
  end
end
