Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  machines = {
    "local"    => "192.168.56.155"
    # ,
    # "production"    => "192.168.56.200",
    # "staging"    => "192.168.56.201",
    # "test"    => "192.168.56.202"
  }

  machines.each do |name, ip|

    config.vm.define name do |machine|

      machine.vm.hostname = name
      machine.vm.network "private_network", ip: ip
      machine.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end

      config.vm.synced_folder "./machines_shared_folder", "/vagrant_data"

      machine.vm.provision "shell", inline: <<-SHELL

        # The -i option means to edit the file in place
        # The -E option enables extended regular expressions, allowing the use of + without escaping it
        # This command looks for lines that may start with spaces, optionally followed by a #,
        # then more spaces, followed by "PasswordAuthentication" and one or more spaces before "no".
        # It replaces the entire matched line with "PasswordAuthentication yes".
        # This command is more flexible and can handle various formatting styles in the sshd_config file
        sudo sed -i -E 's/^[[:space:]]*#?[[:space:]]*PasswordAuthentication[[:space:]]+no/PasswordAuthentication yes/' /etc/ssh/sshd_config

        sudo systemctl restart sshd
        
        echo "vagrant:vagrant" | sudo chpasswd

        # apt-get update

      SHELL

      # machine.vm.provision :ansible do |ansible|
      #   ansible.playbook = "../playbook.yml"
      #   ansible.inventory_path = "../inventories/local"
      #   ansible.become = true
      # end

    end
  end
end
