#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/supervisor

- name: Install Supervisor
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - supervisor

- name: Ensure the supervisor service is started and enable
  ansible.builtin.service:
    name: supervisor
    state: started
    enabled: yes
